language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=b89e0fdcb9223b8aca94b62ec7c6dd48255c50a7ccdd7f029d382308c5febe8d"
install:
  - "npm install grunt-cli codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - "node_modules"
